import type { Metadata } from "next";
import './styles/font.css'
import "./globals.css";
import ClientWrapper from "./ClientWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={`font-clash`}>
        <ClientWrapper>{children}</ClientWrapper>
      </body>
    </html>
  );
}
